"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SenderKeyStore = exports.SignedPreKeyStore = exports.PreKeyStore = exports.IdentityKeyStore = exports.SessionStore = exports.SignalService = exports.registerSignal = void 0;
const signalService_1 = require("./signalService");
Object.defineProperty(exports, "SignalService", { enumerable: true, get: function () { return signalService_1.SignalService; } });
const signal_1 = require("./_aqua/signal");
Object.defineProperty(exports, "registerSignal", { enumerable: true, get: function () { return signal_1.registerSignal; } });
const libsignal_client_1 = require("@signalapp/libsignal-client");
Object.defineProperty(exports, "IdentityKeyStore", { enumerable: true, get: function () { return libsignal_client_1.IdentityKeyStore; } });
Object.defineProperty(exports, "PreKeyStore", { enumerable: true, get: function () { return libsignal_client_1.PreKeyStore; } });
Object.defineProperty(exports, "SenderKeyStore", { enumerable: true, get: function () { return libsignal_client_1.SenderKeyStore; } });
Object.defineProperty(exports, "SessionStore", { enumerable: true, get: function () { return libsignal_client_1.SessionStore; } });
Object.defineProperty(exports, "SignedPreKeyStore", { enumerable: true, get: function () { return libsignal_client_1.SignedPreKeyStore; } });
